### ISSUE TITLE
add SAC admin functionality

### ISSUE THREAD

**Issue by tomerweller** [stellar/soroban-cli#1250]
Stellar asset issuers might need to exercise their administrative privileges in the Soroban context. For example, they might need to revoke or clawback a contract's balance.

Currently, their only option to do that is to write custom code. Adding SAC admin functionality to the CLI can provide them a quick and simple alternative.

**Comment by leighmcculloch** [comment]
SAC admin functionality is accessible via a regular soroban contract invoke, so I think what's missing here for this issue is to make those admin functionalities more convenient. Is what what you're meaning?

For example, using the following flow we can mint an asset with the CLI:

Setup issuer account:

```
$ soroban keys generate me
$ soroban keys address me
GDBVM5YTFVMKS3GI2JGRRV7XMAF7J2WXNFTZ5O5KIK32DNHOSMJLEQFC
```

Deploy asset contract so we can interact with the asset:

```
$ soroban contract asset deploy \
    --asset COIN:GDBVM5YTFVMKS3GI2JGRRV7XMAF7J2WXNFTZ5O5KIK32DNHOSMJLEQFC
CDMNCHZBOQ4UOTLZ3XCSILSCZIMTHTFD2BJLD3WDHOL4UY4I7QJOBL6Q
```

Setup the account that will receive and later get clawed back from:

```
$ soroban keys generate me2
$ soroban keys address me2
GBTCX3BMW45RKJ6T3HQEC66FKFK7H2CRX6BT2BN76R3RGLRWJD2343UE
```

Submit tx to have me2 trust the COIN issued asset:
```
AAAAAgAAAABmK+wstzsVJ9PZ4EF7xVFV8+hRv4M9Bb/0dxMuNkj1vgAAAGQACBp5AAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAABgAAAAFDT0lOAAAAAMNWdxMtWKlsyNJNGNf3YAv06tdpZ567qkK3obTukxKyf/////////8AAAAAAAAAATZI9b4AAABAMHkDUeRZT/RFcAQA0mTT0yijmpVkXQCzSeRppM0myuUvto4rPBYVFMRqgdPs6cJ3Y2ZcpUFIh5JxDV7j1ydOAQ==
```

Mint some of the asset and give it to me2:

```
$ soroban contract invoke \
    --id CDMNCHZBOQ4UOTLZ3XCSILSCZIMTHTFD2BJLD3WDHOL4UY4I7QJOBL6Q \
    -- \
    mint \
    --to GBTCX3BMW45RKJ6T3HQEC66FKFK7H2CRX6BT2BN76R3RGLRWJD2343UE \
    --amount 123
```

It would be convenient if the issuer could perform these operations using the name of their asset, maybe?

For example:

```
$ soroban contract asset invoke \
    --asset COIN:GDBVM5YTFVMKS3GI2JGRRV7XMAF7J2WXNFTZ5O5KIK32DNHOSMJLEQFC \
    -- \
    mint \
    --to GBTCX3BMW45RKJ6T3HQEC66FKFK7H2CRX6BT2BN76R3RGLRWJD2343UE \
    --amount 123
```

It's not that much shorter though.

**Comment by tomerweller** [comment]
I was thinking of your last example, but you make a good point that these things are fairly accessible with invoke as is. Maybe it's a matter of adding a doc resource that's somewhat of a "soroban cheat sheet for asset issuers" and covers using the cli for mint/auth/clawback/etc. 

@janewang wdyt?

**Comment by leighmcculloch** [comment]
Closing since we're addressing this with docs.
