### ISSUE TITLE
CLI: Invoke a contract on network

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-cli#42]
### What problem does your feature solve?

When deploying/managing a contract the dev may wish to call some setup functions (e.g. `contract.init()`). This way they can issue "management" commands and other contract calls to their live contract.

### What would you like to see?

`$ stellar-contract-cli --network testnet call <contract-id> init '<args>'`
(or something)

### What alternatives are there?

Don't do it? Make them use laboratory for now?

**Comment by leighmcculloch** [comment]
The format of the command given the CLI today would be something like:

```
soroban-cli --network testnet invoke --id <contract-id> --fn init --arg ...
```

Where no `--network` option indicates sandbox, and any `--network` option indicates a remove (even locally remote) network.

**Comment by leighmcculloch** [comment]
After giving this issue some more thought in conjunction with #41 and #142, the form of the command would be something like:

1. `soroban-cli invoke --horizon-url <URL> --account <G...> --id <CONTRACTID> --fn <FN> --arg ...`
   - Make a HTTP request to Horizon to get the sequence number of the account.
   - Build a transaction with:
      - Source account set to the given account.
      - Sequence number set to the next sequence number for the source account.
      - One `INVOKE_HOST_FUNCTION` operation that calls the invoke function and includes the given WASM. 
   - Prompt the user to enter the S secret key.
   - Sign the transaction with the S secret key.
   - Submit the transaction to the transaction submission endpoint of the Horizon URL.

2. `soroban-cli invoke --rpc-url <URL> --account <G...> --id <CONTRACTID> --fn <FN> --arg ...`
   - Make a HTTP request to the RPC server to get the sequence number of the account.
   - Build a transaction with:
      - Source account set to the given account.
      - Sequence number set to the next sequence number for the source account.
      - One `INVOKE_HOST_FUNCTION` operation that calls the invoke function and includes the given WASM. 
   - Prompt the user to enter the S secret key.
   - Sign the transaction with the S secret key.
   - Submit the transaction to the `sendTransaction` endpoint of the RPC server.

@paulbellamy @tomerweller Questions:

1. Does the above align with your expectations?
1. Does this align with plans in the RPC server?
1. What will be the preferred flow for invoking, via an RPC server or via Horizon? (So that I can prioritize the respective implementation.)
